WebApplication1/Models/Empleados.cs
namespace WebApplication1.Models
{

    using System;
    using System.Collections.Generic;


    public partial class Empleados
    {
        public int ID { get; set; }
        public string Nombre_Empleado { get; set; }
        public int Cantidad_Hijos { get; set; }
        public int Salario { get; set; }
        public int Bono { get; set; }
    }
}

WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/Usuario.cs
namespace WebApplication1.Models
{
    public class Usuario
    {
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Clave { get; set; }

        public string[] Roles { get; set; }
    }
}

WebApplication1/Controllers/AccesoController.cs
using Microsoft.AspNetCore.Mvc;

using WebApplication1.Models;
using WebApplication1.Data;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;

namespace WebApplication1.Controllers
{
    public class AccesoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(Usuario _usuario)
        {
            DA_Usuario _da_usuario = new DA_Usuario();

            var usuario = _da_usuario.ValidarUsuario(_usuario.Correo,_usuario.Clave);

            if (usuario != null)
            {

                
                #region AUTENTICACTION
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, usuario.Nombre),
                    new Claim("Correo", usuario.Correo),
                };
                foreach (string rol in usuario.Roles) {
                    claims.Add(new Claim(ClaimTypes.Role, rol));
                }
                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
                #endregion


                return RedirectToAction("Index", "Home");
            }
            else {
                return View();
            }
            
        }

        public async Task<IActionResult> Salir()
        {
            
            #region AUTENTICACTION
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            #endregion

            return RedirectToAction("Index");

        }

    }
}

WebApplication1/Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class EmpleadosController : Controller
    {
        private readonly WebApplication1Context _context;

        public EmpleadosController(WebApplication1Context context)
        {
            _context = context;
        }

        // GET: Empleados
        public async Task<IActionResult> Index()
        {
              return View(await _context.Empleados.ToListAsync());
        }

        // GET: Empleados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Empleados == null)
            {
                return NotFound();
            }

            var empleados = await _context.Empleados
                .FirstOrDefaultAsync(m => m.ID == id);
            if (empleados == null)
            {
                return NotFound();
            }

            return View(empleados);
        }

        // GET: Empleados/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Empleados/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Nombre_Empleado,Cantidad_Hijos,Salario,Bono")] Empleados empleados)
        {
            if (ModelState.IsValid)
            {
                _context.Add(empleados);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(empleados);
        }

        // GET: Empleados/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Empleados == null)
            {
                return NotFound();
            }

            var empleados = await _context.Empleados.FindAsync(id);
            if (empleados == null)
            {
                return NotFound();
            }
            return View(empleados);
        }

        // POST: Empleados/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Nombre_Empleado,Cantidad_Hijos,Salario,Bono")] Empleados empleados)
        {
            if (id != empleados.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empleados);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpleadosExists(empleados.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(empleados);
        }

        // GET: Empleados/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Empleados == null)
            {
                return NotFound();
            }

            var empleados = await _context.Empleados
                .FirstOrDefaultAsync(m => m.ID == id);
            if (empleados == null)
            {
                return NotFound();
            }

            return View(empleados);
        }

        // POST: Empleados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Empleados == null)
            {
                return Problem("Entity set 'WebApplication1Context.Empleados'  is null.");
            }
            var empleados = await _context.Empleados.FindAsync(id);
            if (empleados != null)
            {
                _context.Empleados.Remove(empleados);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpleadosExists(int id)
        {
          return _context.Empleados.Any(e => e.ID == id);
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;
using Microsoft.AspNetCore.Authorization;

namespace WebApplication1.Controllers
{
    
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Authorize(Roles = "Administrador,Empleado")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Administrador,Empleado")]
        public IActionResult CRUD()
        {
            return View();
        }

        [Authorize(Roles = "Administrador,Empleado")]
        public IActionResult Pali()
        {
            return View();
        }


        [AllowAnonymous]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Views/Acceso/Index.cshtml
@model Usuario
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>LOGIN</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>

  

    <div class="row mt-5">
        <div class="col-sm-4 offset-sm-4">

         <form asp-controller="Acceso" asp-action="Index" method="post">
              <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Correo Electronico</label>
                <input type="email" class="form-control" asp-for="Correo">
              </div>

              <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Contraseña</label>
                <input type="password" class="form-control" asp-for="Clave">
              </div>

              <button type="submit" class="btn btn-primary">Ingresar</button>
        </form>


        </div>
    </div>

  

</body>
   <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</html>

WebApplication1/Views/Empleados/Create.cshtml
@model WebApplication1.Models.Empleados

@{
    ViewData["Title"] = "Agregar un nuevo empleado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Empleados</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre_Empleado" class="control-label"></label>
                <input asp-for="Nombre_Empleado" class="form-control" />
                <span asp-validation-for="Nombre_Empleado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad_Hijos" class="control-label"></label>
                <input asp-for="Cantidad_Hijos" class="form-control" />
                <span asp-validation-for="Cantidad_Hijos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salario" class="control-label"></label>
                <input asp-for="Salario" class="form-control" />
                <span asp-validation-for="Salario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bono" class="control-label"></label>
                <input asp-for="Bono" class="form-control" />
                <span asp-validation-for="Bono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApplication1/Views/Empleados/Delete.cshtml
@model WebApplication1.Models.Empleados

@{
    ViewData["Title"] = "Eliminar Empleado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Empleados</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre_Empleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre_Empleado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad_Hijos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad_Hijos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bono)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication1/Views/Empleados/Details.cshtml
@model WebApplication1.Models.Empleados

@{
    ViewData["Title"] = "Detalle Empleado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Empleados</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre_Empleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre_Empleado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad_Hijos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad_Hijos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bono)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication1/Views/Empleados/Edit.cshtml
@model WebApplication1.Models.Empleados

@{
    ViewData["Title"] = "Editar Empleado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Empleados</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Nombre_Empleado" class="control-label"></label>
                <input asp-for="Nombre_Empleado" class="form-control" />
                <span asp-validation-for="Nombre_Empleado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad_Hijos" class="control-label"></label>
                <input asp-for="Cantidad_Hijos" class="form-control" />
                <span asp-validation-for="Cantidad_Hijos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salario" class="control-label"></label>
                <input asp-for="Salario" class="form-control" />
                <span asp-validation-for="Salario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bono" class="control-label"></label>
                <input asp-for="Bono" class="form-control" />
                <span asp-validation-for="Bono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

WebApplication1/Views/Empleados/Index.cshtml
@model IEnumerable<WebApplication1.Models.Empleados>

@{
    ViewData["Title"] = "Inicio CRUD";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Empleados</h1>

<p>
    <a asp-action="Create">AGREGAR NUEVO EMPLEADO</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre_Empleado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cantidad_Hijos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bono)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre_Empleado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad_Hijos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bono)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

WebApplication1/Views/Home/CRUD.cshtml
@{
    ViewData["Title"] = "CRUD";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="text-center">
    <div class="alert alert-success">
        <h2 class="display-4">CRUD</h2>
    </div>
    
</div>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <div class="alert alert-success">
        <h2 class="display-4">Bienvenido a Incomel</h2>
    </div>
    
</div>

WebApplication1/Views/Home/Pali.cshtml
@{
    ViewData["Title"] = "Palindromos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="text-center">
    <div class="alert alert-success">
        <h2 class="display-4">Palindromos</h2>
    </div>
    
</div>

WebApplication1/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       
                        
                        @if (User.IsInRole("Administrador") || User.IsInRole("Empleado"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="Index">CRUD</a>
                            </li>
                        }

                        @if (User.IsInRole("Administrador") || User.IsInRole("Empleado"))
                        {
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Pali">Palindromos</a>
                             </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Acceso" asp-action="Salir">Salir</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Prueba Tecnica - Creadora: Reyna Julisa Valiente Arenales
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>